name: flutter_portfolio
description: Root workspace for my Flutter monorepo managed by Melos
version: 0.0.1

environment:
  sdk: ^3.8.1

dev_dependencies:
  melos: ^6.3.3

dependencies:
  bloc: ^9.0.0
  flutter_bloc: ^9.1.1
  # Optional, falls du lokale Pfade erzwingen willst - meist nicht n√∂tig bei melos bootstrap
  # Wird von Melos automatisch generiert

